# Generated by Django 4.2.6 on 2024-02-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('name', models.CharField(max_length=150)),
                ('language', models.CharField(max_length=20)),
                ('creation_dttm', models.DateTimeField()),
                ('access_mode', models.IntegerField(choices=[(0, 'Public'), (1, 'Private'), (2, 'Password')])),
                ('password', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
