# Generated by Django 4.2.6 on 2024-02-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paste',
            name='password',
        ),
        migrations.AlterField(
            model_name='paste',
            name='access_mode',
            field=models.IntegerField(choices=[(0, 'public'), (1, 'private')]),
        ),
    ]
