# Generated by Django 4.2.6 on 2024-02-17 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0002_initial'),
        ('comment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='paste',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='paste.paste'),
            preserve_default=False,
        ),
    ]
